---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: ant
  assert:
    that:
      - ansible_os_family in ['Archlinux', 'Debian', 'RedHat', 'Suse']

- name: Install Ant installation directory
  tags: ant
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ ant_install_dir }}


- name: Install Ant
  tags: ant
  unarchive:
    src: "{{ ant_url }}/{{ant_filename }}"
    dest: "{{ ant_install_dir }}"
    remote_src: true

- name: Install Ant bin directory
  tags: ant
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ ant_bin_path }}

- name: Install Ant binary
  tags: ant
  file:
    state=link
    force=true
    src={{ ant_install_dir }}/{{ant_filename|splitext}}[0]/bin/ant
    dest={{ ant_bin_path }}/ant

- name: download antlibs
  get_url: url='{{ item.url }}' dest='{{ ant_install_dir }}/apache-ant-{{ ant_version }}/lib/{{ item.name}}-{{ item.version }}.jar'
    with_items:
      - "{{ antlib_jars }}"
  when: antlib_jars is defined
